### ISSUE TITLE
Plans to release model outputs?

### ISSUE THREAD

**Issue by shatu** [esteng/regal_program_learning#1]
Hi,

Interesting work! Are there any plans to release the model outputs (especially the final contents of CodeBank, DemoBank, and the test set solutions that use these helper functions) for the datasets studied in the paper?

**Comment by esteng** [comment]
Hi -- I've just uploaded the output directories here: https://github.com/esteng/regal_program_learning/blob/main/data/README.md

**Comment by shatu** [comment]
Thanks! :)
